package com.quizverse.app.util

import java.time.LocalDate

/**
 * 365 daily motivational quotes for the QuizVerse home screen.
 * One unique quote per day of the year, cycling annually.
 */
object DailyQuotes {

    fun randomQuote(exclude: String? = null): String {
        if (exclude == null) return quotes.random()
        var next: String
        do { next = quotes.random() } while (next == exclude)
        return next
    }

    private val quotes = listOf(
        // --- Januar (1-31) ---
        "Wissen ist die einzige Ressource, die sich vermehrt, wenn man sie teilt.",
        "Jede Frage, die du beantwortest, macht dich klueger.",
        "Der Weg zum Wissen beginnt mit einer einzigen Frage.",
        "Neugier ist der Schluessel zu allem Wissen.",
        "Heute ist ein guter Tag, um etwas Neues zu lernen!",
        "Wer fragt, bleibt nicht dumm.",
        "Dein Gehirn liebt Herausforderungen \u2014 gib ihm eine!",
        "Jedes Quiz bringt dich einen Schritt weiter.",
        "Bildung ist die maechtigste Waffe der Welt.",
        "Lerne, als wuerdest du ewig leben.",
        "Wissen ist wie ein Muskel \u2014 trainiere ihn taeglich!",
        "Die besten Ideen kommen aus neugierigen Koepfen.",
        "Ein Tag ohne Lernen ist ein verlorener Tag.",
        "Stelle dich der Herausforderung \u2014 du kannst mehr als du denkst!",
        "Wissen macht nicht nur klug, sondern auch mutig.",
        "Fehler sind die besten Lehrer \u2014 trau dich!",
        "Jede richtige Antwort ist ein kleiner Sieg.",
        "Dein Wissen von heute formt dein Morgen.",
        "Lernen ist ein Abenteuer \u2014 geniesse die Reise!",
        "Je mehr du weisst, desto mehr siehst du.",
        "Wissen oeffnet Tueren, die du noch gar nicht kennst.",
        "Sei neugierig, sei mutig, sei schlau!",
        "Heute Abend weisst du mehr als heute Morgen.",
        "Ein kluger Kopf hat nie genug Fragen.",
        "Wer aufhoert zu lernen, hoert auf zu wachsen.",
        "Du bist nur ein Quiz entfernt von neuem Wissen!",
        "Mach jeden Tag zu deinem Lerntag.",
        "Die Welt gehoert den Neugierigen.",
        "Starte jetzt \u2014 dein Gehirn wartet schon!",
        "Wissen sammeln macht suechtig \u2014 im besten Sinne!",
        "Jede Frage ist eine Chance, etwas zu entdecken.",

        // --- Februar (32-59) ---
        "Denken ist die schwerste Arbeit \u2014 deshalb tun es so wenige.",
        "Wer neugierig bleibt, bleibt jung im Kopf.",
        "Ein Quiz am Tag haelt die Langeweile fern.",
        "Wissen ist Macht \u2014 nutze sie weise!",
        "Der kluge Mensch lernt aus allem und von jedem.",
        "Dein Potenzial ist grenzenlos \u2014 entdecke es!",
        "Jede Antwort fuehrt zu einer neuen Frage.",
        "Das Gehirn ist der beste Computer \u2014 update es regelmaessig!",
        "Wissen waechst, wenn du es teilst.",
        "Heute schon etwas Neues gelernt? Los geht's!",
        "Intelligenz ist nicht das Wissen selbst, sondern die Vorstellungskraft.",
        "Wer liest, reist \u2014 auch ohne sich zu bewegen.",
        "Jedes Wissensgebiet hat seine eigene Schoenheit.",
        "Habe Mut, deinen eigenen Verstand zu gebrauchen!",
        "Lernen ist keine Pflicht, sondern ein Geschenk.",
        "Der Anfang ist die Haelfte des Ganzen.",
        "Manche Antworten findest du nur, wenn du fragst.",
        "Wissen verbindet Menschen ueber alle Grenzen hinweg.",
        "Dein naechster Aha-Moment wartet schon!",
        "Wer nichts weiss, muss alles glauben.",
        "Bildung ist der Reisepass in die Zukunft.",
        "Jede Stunde Lernen ist eine Investition in dich selbst.",
        "Das Schoene am Lernen: Es hoert nie auf.",
        "Teste dein Wissen \u2014 ueberrasche dich selbst!",
        "Ein neugieriger Geist ist ein reicher Geist.",
        "Wissen ist der Kompass auf deiner Lebensreise.",
        "Nicht das Wissen allein, sondern das Anwenden zaehlt.",
        "Heute ist der perfekte Tag fuer ein Quiz!",

        // --- Maerz (60-90) ---
        "Lernen ist wie Rudern gegen den Strom \u2014 wer aufhoert, treibt zurueck.",
        "Dein Wissen ist dein groesster Schatz.",
        "Jede neue Information ist ein Puzzleteil deines Weltbildes.",
        "Gib niemals auf zu lernen \u2014 das Leben gibt nie auf zu lehren.",
        "Wissen schafft Vertrauen, Vertrauen schafft Erfolg.",
        "Die Investition in Wissen zahlt die besten Zinsen.",
        "Ein Buch, ein Quiz, eine neue Erkenntnis \u2014 jeden Tag!",
        "Wer viel fragt, bekommt viele Antworten.",
        "Dein Verstand kennt keine Grenzen \u2014 challenge ihn!",
        "Wissen ist die Bruecke zwischen Traeumen und Wirklichkeit.",
        "Jeder Experte war einmal ein Anfaenger.",
        "Lernen macht gluecklich \u2014 das ist wissenschaftlich bewiesen!",
        "Das Beste, was du heute tun kannst: etwas Neues lernen.",
        "Wissen ist wie Licht \u2014 es vertreibt die Dunkelheit.",
        "Bleib hungrig nach Wissen, bleib bescheiden im Erfolg.",
        "Dein Gehirn dankt es dir \u2014 gib ihm Futter!",
        "Kleine Schritte fuehren zu grossen Erkenntnissen.",
        "Die Neugier hat ihren eigenen Grund zu existieren.",
        "Wissen ist keine Last, sondern Fluegel.",
        "Jede Minute Lernen ist eine Minute gut investiert.",
        "Denke gross, lerne taeglich, wachse stetig!",
        "Die klügsten Menschen stellen die einfachsten Fragen.",
        "Heute ein Quiz, morgen ein Gespraechsthema mehr!",
        "Wissen ist der Samen, Anwendung die Ernte.",
        "Nicht die Antwort zaehlt, sondern der Weg dahin.",
        "Dein Wissensvorsprung beginnt mit dem ersten Klick.",
        "Lernen ist die Superkraft, die jeder hat.",
        "Lass dich inspirieren \u2014 von Fragen und Antworten!",
        "Wer lernt, veraendert die Welt \u2014 angefangen bei sich selbst.",
        "Jeden Tag ein bisschen schlauer \u2014 das ist das Ziel!",
        "Wissen macht das Leben bunter und reicher.",

        // --- April (91-120) ---
        "Ein offener Geist ist der Anfang allen Wissens.",
        "Deine Neugierde ist dein bester Lehrer.",
        "Wissen roestet nicht \u2014 im Gegenteil!",
        "Fragen sind die Antworten der Klugen.",
        "Jeden Tag eine neue Chance, etwas zu entdecken.",
        "Das Wissen von heute ist die Innovation von morgen.",
        "Lernst du noch oder weisst du schon?",
        "Wer denkt, gewinnt \u2014 das gilt auch beim Quiz!",
        "Bildung ist nicht das Fuellen eines Eimers, sondern das Entzuenden eines Feuers.",
        "Dein naechstes Lieblingsthema wartet auf dich!",
        "Wissen ist wie eine Reise \u2014 der Weg ist das Ziel.",
        "Heute neu gelernt, morgen schon angewendet!",
        "Die wichtigste Investition ist die in den eigenen Kopf.",
        "Jedes Quiz ist ein kleines Abenteuer!",
        "Wissen verdoppelt sich, wenn man es weitergibt.",
        "Sei der Mensch, der immer eine Antwort kennt!",
        "Dein Wissensdurst ist dein Motor.",
        "Lernen oeffnet Horizonte, die vorher unsichtbar waren.",
        "Wer neugierig ist, wird nie gelangweilt sein.",
        "Die beste Zeit zum Lernen ist jetzt \u2014 immer jetzt!",
        "Wissen gibt dir die Freiheit, eigene Entscheidungen zu treffen.",
        "Mach dein Gehirn zum staerksten Muskel!",
        "Jede Antwort macht dich ein Stueck weiser.",
        "Lernen ist der Schluessel zu jeder verschlossenen Tuer.",
        "Dein Wissen ist einzigartig \u2014 so wie du!",
        "Wer viel weiss, hat viel zu erzaehlen.",
        "Heute ist Quiztag \u2014 mach das Beste draus!",
        "Wissen ist die beste Verteidigung gegen Langeweile.",
        "Neues Wissen, neue Perspektiven, neue Moeglichkeiten!",
        "Dein Kopf ist der grossartigste Speicher der Welt.",

        // --- Mai (121-151) ---
        "Lernen hoert nie auf \u2014 und das ist wunderbar!",
        "Wissen ist die Waehrung der Zukunft.",
        "Jeder kluge Gedanke begann mit einer Frage.",
        "Dein Wissensnetzwerk waechst mit jedem Quiz.",
        "Die Welt ist voller Wunder \u2014 entdecke sie!",
        "Wer lernt, lebt doppelt.",
        "Wissen macht dich nicht nur klueger, sondern auch interessanter.",
        "Heute ein Quizheld, morgen ein Wissensgenie!",
        "Die besten Gespraeche beginnen mit: Wusstest du schon...?",
        "Jedes neue Wort ist ein neues Werkzeug.",
        "Wissen ist die Bruecke zwischen Gestern und Morgen.",
        "Dein Gehirn ist hungrig \u2014 fuettere es mit Wissen!",
        "Lernen ist die schooenste Form der Selbstverbesserung.",
        "Wer fragt, fuehrt \u2014 auch sich selbst!",
        "Jedes Quiz ist ein Training fuer den Geist.",
        "Wissen veraendert nicht die Welt \u2014 aber die, die es haben.",
        "Stell dir vor, was du morgen alles wissen wirst!",
        "Die Neugier ist die Mutter aller Erfindungen.",
        "Wissen kennt keine Altersgrenzen.",
        "Ein kluger Kopf ist das beste Kapital.",
        "Lerne mit Freude \u2014 es bleibt besser haengen!",
        "Dein Wissensschatz waechst mit jedem Tag.",
        "Die Antwort liegt oft naeher als du denkst.",
        "Wissen ist portabel \u2014 nimm es ueberallhin mit!",
        "Heute gelernt, fuer immer gewusst.",
        "Dein Verstand ist bereit \u2014 bist du es auch?",
        "Wissen teilen heisst Freude teilen.",
        "Jede Frage bringt dich dem Verstaendnis naeher.",
        "Der Weg zum Experten beginnt mit dem ersten Quiz.",
        "Wissen ist die Flamme, die nie erlischt.",
        "Mach dir die Welt zum Klassenzimmer!",

        // --- Juni (152-181) ---
        "Sommer und Lernen? Passt perfekt zusammen!",
        "Wissen ist die beste Sonnencreme fuer den Geist.",
        "Jeder Sonnenstrahl bringt eine neue Erkenntnis.",
        "Entspannt lernen \u2014 das geht am besten mit einem Quiz!",
        "Die laengsten Tage sind perfekt fuer neue Entdeckungen.",
        "Wissen ist erfrischend wie ein kuehles Getraenk.",
        "Dein Gehirn braucht keinen Urlaub vom Lernen!",
        "Nutze die langen Abende fuer kurze Quizrunden.",
        "Wissen sammeln ist wie Muscheln suchen am Strand.",
        "Jede Jahreszeit hat ihre eigenen Lektionen.",
        "Lerne heute, glaenze morgen!",
        "Wissen ist der Schatten, der dich nie verlaesst.",
        "Dein Gehirn ist der beste Reisebegleiter.",
        "Neue Fragen, neue Antworten, neues Glueck!",
        "Wissen ist die Landkarte deines Lebens.",
        "Jeden Tag ein Stueckchen weiser werden.",
        "Die besten Entdeckungen macht man zufaellig \u2014 beim Quizzen!",
        "Wissen gibt dir Fluegel \u2014 auch ohne Flugzeug.",
        "Lerne spielerisch \u2014 es funktioniert am besten!",
        "Dein Wissensgarten braucht taegliche Pflege.",
        "Wer lernt, erntet \u2014 frueher oder spaeter.",
        "Wissen ist der beste Eisbrecher auf jeder Party.",
        "Heute mutig fragen, morgen klug antworten.",
        "Dein naechster Wissens-Durchbruch ist naeher als du denkst!",
        "Lernen macht den Unterschied zwischen Traeumen und Tun.",
        "Wissen ist die Zutat, die jedem Gespraech Wuerze gibt.",
        "Sei stolz auf jede richtige Antwort!",
        "Die Welt belohnt die Wissbegierigen.",
        "Heute ist der beste Tag, um anzufangen.",
        "Wissen ist wie Honig \u2014 suess und wertvoll!",

        // --- Juli (182-212) ---
        "Mitten im Sommer, mitten im Lernen!",
        "Wissen kuehlt den Kopf und waermt das Herz.",
        "Jeder Tag ist eine neue Seite im Buch des Wissens.",
        "Dein Gehirn ist das beste Freibad \u2014 tauch ein!",
        "Wissen ist der Kompass, der nie die Richtung verliert.",
        "Lernen unter freiem Himmel \u2014 warum nicht?",
        "Jede Antwort ist ein kleiner Applaus fuer dein Gehirn.",
        "Wissen macht Sommer noch schoener.",
        "Die besten Ideen kommen in entspannten Momenten.",
        "Quiz am Pool? Warum nicht!",
        "Wissen ist wie Eis \u2014 am besten taeglich geniessen.",
        "Dein Kopf kennt keine Sommerpause.",
        "Lernen ist die schoenste Art, Zeit zu verbringen.",
        "Jeder Tag bringt 24 Stunden voller Moeglichkeiten.",
        "Wissen ist der Anker in stuermischen Zeiten.",
        "Sei der Held deiner eigenen Wissensgeschichte!",
        "Lernen macht nicht muede \u2014 es macht wach!",
        "Dein Wissensbaum traegt jeden Tag neue Fruechte.",
        "Die beste Investition: Zeit fuers Lernen.",
        "Wissen ist der Diamant, den niemand stehlen kann.",
        "Heute gelernt, morgen angewendet, uebermorgen gemeistert!",
        "Dein Gehirn ist ein Wunderwerk \u2014 fordere es heraus!",
        "Wissen verbindet Herz und Verstand.",
        "Jede neue Erkenntnis ist ein Geschenk an dich selbst.",
        "Lernen ist der Weg, Staunen das Ziel.",
        "Wissen kennt keine Grenzen \u2014 genau wie dein Potenzial!",
        "Sei ein Entdecker \u2014 jeden einzelnen Tag!",
        "Die klügsten Koepfe sind die neugierigsten.",
        "Wissen ist die Melodie deines Verstandes.",
        "Heute quizzen, morgen glaenzen!",
        "Dein Wissenshunger ist deine Staerke.",

        // --- August (213-243) ---
        "Der Sommer geht, das Wissen bleibt!",
        "Jeder Abend ist eine Chance fuer ein Quiz.",
        "Wissen ist das Licht am Ende des Tunnels.",
        "Dein Gehirn ist bereit fuer neue Abenteuer!",
        "Lernen ist keine Last \u2014 es ist ein Privileg.",
        "Die besten Geschichten beginnen mit Wissen.",
        "Wer lernt, hat immer etwas zu erzaehlen.",
        "Dein Wissensrucksack wird nie zu schwer.",
        "Jede Frage ist ein Schluessel zu einer neuen Welt.",
        "Wissen macht gluecklich \u2014 probier es aus!",
        "Die Welt braucht neugierige Koepfe wie dich!",
        "Lernen ist der beste Weg, sich selbst zu ueberraschen.",
        "Wissen ist wie ein guter Freund \u2014 immer da, wenn du es brauchst.",
        "Heute ein Quiz, morgen ein Gespraech, das beeindruckt.",
        "Dein Verstand waechst mit jeder Herausforderung.",
        "Wissen ist die Wurzel allen Fortschritts.",
        "Mach Wissen zu deiner taeglichen Gewohnheit!",
        "Jede richtige Antwort staerkt dein Selbstvertrauen.",
        "Lernen oeffnet Tueren \u2014 eine nach der anderen.",
        "Wissen ist der beste Begleiter auf Reisen.",
        "Dein naechstes Aha-Erlebnis wartet im naechsten Quiz!",
        "Die Welt ist ein Buch \u2014 lies jeden Tag eine Seite.",
        "Wissen ist die Kraft, die von innen kommt.",
        "Sei hungrig nach Wissen \u2014 nie satt!",
        "Jeder Tag bietet 86.400 Sekunden zum Lernen.",
        "Wissen ist die Sprache, die alle verstehen.",
        "Dein Kopf ist voller Potenzial \u2014 entfalte es!",
        "Lernen ist der Soundtrack deines Lebens.",
        "Wissen macht stark \u2014 innerlich und aeusserlich.",
        "Die besten Quizzer sind die neugierigsten Menschen.",
        "Heute ist dein Tag \u2014 lerne etwas Grossartiges!",

        // --- September (244-273) ---
        "Der Herbst des Wissens traegt die reichsten Fruechte.",
        "Neue Jahreszeit, neue Lernchancen!",
        "Wissen ist wie buntes Herbstlaub \u2014 vielfaeltig und schoen.",
        "Dein Gehirn blueht auch im Herbst!",
        "Lernen ist die beste Erntedank-Tradition.",
        "Jeder kuehle Abend ist perfekt fuer ein Quiz.",
        "Wissen waermt von innen \u2014 besser als jeder Tee!",
        "Der Herbst erinnert uns: Veraenderung ist Wachstum.",
        "Dein Wissensbaum verliert nie seine Blaetter.",
        "Lernen in der Kuschelzeit \u2014 gibt es etwas Besseres?",
        "Wissen ist der goldene Oktober deines Geistes.",
        "Jede Frage ist ein Samenkorn fuer zukuenftige Erkenntnis.",
        "Die besten Ideen reifen wie guter Wein.",
        "Dein Kopf kennt keine Jahreszeiten \u2014 er lernt immer!",
        "Wissen macht den Unterschied zwischen Sehen und Verstehen.",
        "Herbstzeit ist Lesezeit \u2014 und Quizzeit!",
        "Jede Antwort ist ein Blatt mehr an deinem Wissensbaum.",
        "Lernen ist die schoenste Herbstbeschaeftigung.",
        "Wissen faerbt dein Leben in bunten Farben.",
        "Der kluge Kopf bereitet sich im Herbst auf den Winter vor.",
        "Dein Wissensvorrat kennt kein Verfallsdatum.",
        "Heute lernen, morgen ernten, uebermorgen teilen!",
        "Wissen ist die waermste Decke fuer kuehle Tage.",
        "Jedes Quiz ist ein Spaziergang durch die Welt des Wissens.",
        "Sei wie der Herbst \u2014 lass los, was du nicht brauchst, behalte was zaehlt!",
        "Wissen ist die Ernte deiner Neugier.",
        "Dein Gehirn ist der beste Heizkoerper \u2014 halte es warm mit Wissen!",
        "Lernen macht jeden Tag zum goldenen Oktober.",
        "Die besten Erkenntnisse kommen in stillen Momenten.",
        "Wissen ist das Licht, das den Herbstnebel durchbricht.",

        // --- Oktober (274-304) ---
        "Oktober \u2014 der Monat der grossen Fragen!",
        "Wissen gruselt sich nie \u2014 auch nicht an Halloween.",
        "Jede Frage ist ein kleines Raetsel zum Loesen.",
        "Dein Gehirn feiert jeden Tag Halloween \u2014 es liebt Ueberraschungen!",
        "Wissen ist der Zauber, den jeder lernen kann.",
        "Lernen ist wie Kuerbisschnitzen \u2014 am Ende leuchtet es!",
        "Die dunkleren Tage sind perfekt zum Wissensammeln.",
        "Jede Antwort vertreibt ein Stueckchen Unwissenheit.",
        "Wissen ist das Licht deiner inneren Laterne.",
        "Sei mutig \u2014 auch bei schwierigen Fragen!",
        "Dein Wissensschatz wird nie von Gespenstern gestohlen.",
        "Lernen ist magisch \u2014 und du bist der Zauberer!",
        "Wissen macht aus jedem Abend einen Filmabend im Kopf.",
        "Jede Frage ist ein Tueroeffner zu neuen Welten.",
        "Oktober lehrt uns: Auch in der Dunkelheit steckt Schoenheit.",
        "Dein Gehirn ist der beste Gruselfilm-Regisseur \u2014 voller Ueberraschungen!",
        "Wissen ist suess \u2014 ganz ohne Kalorien!",
        "Heute ein Quiz, morgen eine neue Faehigkeit.",
        "Die besten Geschichten schreibt das Wissen.",
        "Jeder Tag ist ein unbeschriebenes Kapitel \u2014 fuell es mit Wissen!",
        "Wissen vertreibt die Angst vor dem Unbekannten.",
        "Dein Verstand ist staerker als jeder Geist!",
        "Lernen ist die Taschenlampe im Dunkeln.",
        "Wissen gibt dir Superkraefte \u2014 unsichtbar aber maechtig!",
        "Sei neugierig wie ein Kind, weise wie ein Erwachsener.",
        "Jede Erkenntnis ist ein Schritt naeher am Ziel.",
        "Wissen ist die Maske, die nie verrutscht.",
        "Dein Quiz-Abenteuer beginnt mit einem Klick!",
        "Die kuerzeren Tage machen das Lernen gemuetlicher.",
        "Wissen ist wie Kerzenlicht \u2014 es waermt und erleuchtet.",
        "Heute mutig quizzen \u2014 keine Angst vor falschen Antworten!",

        // --- November (305-334) ---
        "November \u2014 Zeit fuer tiefe Gedanken und kluges Wissen.",
        "Wissen ist die beste Gesellschaft an langen Abenden.",
        "Jeder Regentropfen bringt eine neue Idee.",
        "Dein Gehirn blueht auch ohne Sonnenschein!",
        "Lernen ist der waermste Pullover fuer den Geist.",
        "Wissen macht graue Tage bunt.",
        "Die stillen Monate sind perfekt zum Nachdenken.",
        "Jede Frage ist ein Fenster in eine andere Welt.",
        "Wissen ist die Heizung deines Verstandes.",
        "Dein Wissensfeuer brennt auch im November!",
        "Lernen ist wie heisse Schokolade \u2014 waermt und macht gluecklich.",
        "Die besten Erkenntnisse kommen an regnerischen Tagen.",
        "Wissen ist der Regenschirm fuer schwierige Zeiten.",
        "Jeder Tag hat genug Licht zum Lernen.",
        "Dein Gehirn kennt keinen Winterschlaf.",
        "Wissen ist das Feuer, das nie ausgeht.",
        "Nutze die Gemuetlichkeit zum Wissenaufbau!",
        "Jede Antwort ist ein Stern am Novemberhimmel.",
        "Lernen verbindet die Herzen und die Koepfe.",
        "Wissen ist dankbar \u2014 es bleibt bei dir!",
        "Die Natur ruht, dein Geist darf weiterwachsen.",
        "Jedes Quiz ist ein kleines Glueck im Alltag.",
        "Wissen ist der Leuchtturm in der Dunkelheit.",
        "Dein Verstand ist wie ein Kamin \u2014 je mehr du reinlegst, desto waermer wird es.",
        "Lernen macht den November zum Wissens-November!",
        "Die besten Buecher und Quizze warten auf dich.",
        "Wissen ist die Bruecke ueber jedes Tief.",
        "Sei dankbar fuer jeden neuen Gedanken.",
        "Dein Wissensweg fuehrt immer vorwaerts.",
        "November-Weisheit: Ruhe ist die Schwester des Lernens.",

        // --- Dezember (335-365) ---
        "Dezember \u2014 das Jahr in Wissen zusammenfassen!",
        "Wissen ist das schoenste Geschenk unter dem Baum.",
        "Jeder Tag im Advent bringt neue Erkenntnisse.",
        "Dein Gehirn feiert mit \u2014 gib ihm ein Wissensgeschenk!",
        "Lernen im Kerzenschein \u2014 magisch!",
        "Wissen ist der Stern, dem die Weisen folgen.",
        "Die festliche Zeit ist perfekt fuer kluge Gespraeche.",
        "Jede Frage ist eine Kerze am Adventskranz des Wissens.",
        "Wissen glaenzt heller als jede Weihnachtskugel.",
        "Dein Wissens-Adventskalender hat 365 Tuerchen!",
        "Lernen ist das Geschenk, das du dir selbst machst.",
        "Die besten Vorsaetze beginnen mit Wissen.",
        "Wissen ist wie Schnee \u2014 es verwandelt die Welt.",
        "Jeder letzte Tag im Jahr ist der erste Tag neuen Wissens.",
        "Dein Gehirn braucht keine Winterpause!",
        "Wissen macht die Feiertage noch schoener.",
        "Die gemuetlichste Zeit ist die beste Lernzeit.",
        "Jede Antwort ist ein Geschenk an dich selbst.",
        "Wissen ist die Melodie der Weihnachtszeit.",
        "Dein Jahresrueckblick: So viel gelernt, so viel gewachsen!",
        "Lernen kennt keine Feiertage \u2014 und das ist gut so!",
        "Wissen ist der beste Silvester-Vorsatz.",
        "Die letzten Tage des Jahres gehoeren den besten Fragen.",
        "Dein Wissenstagebuch ist voller Eintraege \u2014 sei stolz!",
        "Wissen verbindet alte und neue Jahre.",
        "Jedes Ende ist ein neuer Anfang \u2014 auch beim Lernen.",
        "Dein Gehirn hat dieses Jahr Grossartiges geleistet!",
        "Wissen ist die Rakete ins neue Jahr.",
        "Auf ein neues Jahr voller Fragen, Antworten und Wissen!",
        "Silvester-Weisheit: Das Beste liegt immer noch vor dir.",
        "365 Tage Wissen \u2014 und morgen geht es weiter!"
    )
}
