import { sql } from "drizzle-orm";
import { bigint, boolean, index, integer, jsonb, pgTable, primaryKey, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";

const auditColumns = { createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() };
export const organizations = pgTable("organizations", { id: uuid("id").primaryKey(), name: text("name").notNull(), slug: text("slug").notNull().unique(), status: text("status").notNull().default("active"), ...auditColumns });
export const users = pgTable("users", { id: uuid("id").primaryKey(), email: text("email").notNull().unique(), displayName: text("display_name").notNull(), passwordHash: text("password_hash"), locale: text("locale").notNull().default("de-DE"), timeZone: text("time_zone").notNull().default("Europe/Berlin"), ...auditColumns });
export const memberships = pgTable("memberships", { organizationId: uuid("organization_id").notNull().references(() => organizations.id), userId: uuid("user_id").notNull().references(() => users.id), role: text("role").notNull(), status: text("status").notNull().default("active"), ...auditColumns }, (table) => [primaryKey({ columns: [table.organizationId, table.userId] })]);
export const sessions = pgTable("sessions", { id: uuid("id").primaryKey(), userId: uuid("user_id").notNull().references(() => users.id), organizationId: uuid("organization_id").notNull().references(() => organizations.id), tokenHash: text("token_hash").notNull().unique(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), revokedAt: timestamp("revoked_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), lastActiveAt: timestamp("last_active_at", { withTimezone: true }).notNull().defaultNow() });
export const userPreferences = pgTable("user_preferences", { userId: uuid("user_id").notNull().references(() => users.id), organizationId: uuid("organization_id").notNull().references(() => organizations.id), revision: integer("revision").notNull().default(0), values: jsonb("values").notNull().default({}), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [primaryKey({ columns: [table.userId, table.organizationId] })]);
export const projects = pgTable("projects", { id: uuid("id").primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id), name: text("name").notNull(), type: text("type").notNull(), fidelity: text("fidelity").notNull(), platforms: jsonb("platforms").notNull(), status: text("status").notNull().default("active"), ownerId: uuid("owner_id").notNull().references(() => users.id), activeVersion: integer("active_version").notNull().default(1), revision: integer("revision").notNull().default(0), deletedAt: timestamp("deleted_at", { withTimezone: true }), ...auditColumns }, (table) => [index("projects_hub_idx").on(table.organizationId, table.status, table.updatedAt)]);
export const projectImports = pgTable("project_imports", { projectId: uuid("project_id").primaryKey().references(() => projects.id), organizationId: uuid("organization_id").notNull().references(() => organizations.id), format: text("format").notNull(), entryPath: text("entry_path").notNull(), objectPrefix: text("object_prefix").notNull(), manifest: jsonb("manifest").$type<Array<{ path: string; size: number; mime: string }>>().notNull(), fileCount: integer("file_count").notNull(), totalBytes: bigint("total_bytes", { mode: "number" }).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [index("project_imports_org_idx").on(table.organizationId, table.createdAt)]);
export const providerConnections = pgTable("provider_connections", { id: uuid("id").primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id), provider: text("provider").notNull(), status: text("status").notNull().default("connected"), credentials: text("credentials").notNull(), accountId: text("account_id"), email: text("email"), expiresAt: timestamp("expires_at", { withTimezone: true }), settings: jsonb("settings").$type<{ model?: string; effort?: string; fast?: boolean; models?: unknown[] }>().notNull().default({}), isDefault: boolean("is_default").notNull().default(false), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [uniqueIndex("provider_connection_org_unique").on(table.organizationId, table.provider), uniqueIndex("provider_connection_one_default").on(table.organizationId).where(sql`${table.isDefault} = true`)]);
export const drafts = pgTable("drafts", { id: uuid("id").primaryKey(), projectId: uuid("project_id").notNull().references(() => projects.id), organizationId: uuid("organization_id").notNull().references(() => organizations.id), revision: integer("revision").notNull().default(0), document: jsonb("document").notNull(), updatedBy: uuid("updated_by").notNull().references(() => users.id), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [uniqueIndex("draft_project_unique").on(table.projectId)]);
export const designOperations = pgTable("design_operations", { id: uuid("id").primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id), projectId: uuid("project_id").notNull().references(() => projects.id), draftId: uuid("draft_id").notNull().references(() => drafts.id), revision: integer("revision").notNull(), actionId: uuid("action_id").notNull(), actorId: uuid("actor_id").notNull().references(() => users.id), operations: jsonb("operations").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [uniqueIndex("design_operation_revision_unique").on(table.draftId, table.revision), uniqueIndex("design_operation_action_unique").on(table.draftId, table.actionId)]);
export const versions = pgTable("versions", { id: uuid("id").primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id), projectId: uuid("project_id").notNull().references(() => projects.id), number: integer("number").notNull(), parentId: uuid("parent_id"), reason: text("reason").notNull(), authorId: uuid("author_id").notNull().references(() => users.id), document: jsonb("document").notNull(), snapshotHash: text("snapshot_hash").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [uniqueIndex("version_number_unique").on(table.projectId, table.number)]);
// Vor jeder KI-Aenderung wird der bisherige Stand der betroffenen Dateien gesichert. Ohne diese
// Sicherung gaebe es keinen Weg zurueck, wenn ein Lauf das Design verschlechtert — und genau dieser
// Rueckweg entscheidet, ob man der KI ueberhaupt „freie Hand" geben mag.
export const designSnapshots = pgTable("design_snapshots", { id: uuid("id").primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id), projectId: uuid("project_id").notNull().references(() => projects.id), revision: integer("revision").notNull(), label: text("label").notNull(), files: jsonb("files").$type<Array<{ path: string; mime: string; content: string }>>().notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [index("design_snapshot_project_idx").on(table.projectId, table.createdAt)]);
export const auditEvents = pgTable("audit_events", { id: uuid("id").primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id), actorId: uuid("actor_id").references(() => users.id), action: text("action").notNull(), targetType: text("target_type").notNull(), targetId: uuid("target_id"), result: text("result").notNull(), metadata: jsonb("metadata").notNull().default({}), correlationId: uuid("correlation_id").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [index("audit_lookup_idx").on(table.organizationId, table.createdAt, table.action)]);
export const outboxEvents = pgTable("outbox_events", { id: uuid("id").primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id), aggregateId: uuid("aggregate_id").notNull(), type: text("type").notNull(), payload: jsonb("payload").notNull(), attempts: integer("attempts").notNull().default(0), availableAt: timestamp("available_at", { withTimezone: true }).notNull().defaultNow(), processedAt: timestamp("processed_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [index("outbox_pending_idx").on(table.processedAt, table.availableAt)]);
export const jobs = pgTable("jobs", { id: uuid("id").primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id), projectId: uuid("project_id").references(() => projects.id), kind: text("kind").notNull(), status: text("status").notNull(), progress: integer("progress").notNull().default(0), idempotencyKey: text("idempotency_key").notNull(), input: jsonb("input").notNull(), result: jsonb("result"), errorCode: text("error_code"), attempts: integer("attempts").notNull().default(0), cancelRequested: boolean("cancel_requested").notNull().default(false), heartbeatAt: timestamp("heartbeat_at", { withTimezone: true }), ...auditColumns }, (table) => [uniqueIndex("job_idempotency_unique").on(table.organizationId, table.kind, table.idempotencyKey)]);
export const usageRecords = pgTable("usage_records", { id: uuid("id").primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id), projectId: uuid("project_id").references(() => projects.id), userId: uuid("user_id").references(() => users.id), category: text("category").notNull(), quantity: bigint("quantity", { mode: "number" }).notNull(), unit: text("unit").notNull(), amountMicros: bigint("amount_micros", { mode: "number" }).notNull().default(0), currency: text("currency").notNull().default("EUR"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
