using System;
using System.Collections.Generic;
using System.IO;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Media;
using System.Windows.Threading;
using TerminalVoiceOverlay.Services;

namespace TerminalVoiceOverlay.Views;

public sealed record PromptEditResult(
    string ShortLabel,
    string OriginalText,
    bool IsAlwaysOn,
    bool IsPrePrompt,
    bool IsPostPrompt,
    int? HotkeyNumber);

public partial class PromptEditDialog : Window
{
    public PromptEditResult? Result { get; private set; }

    /// <summary>
    /// Original text BEFORE Gemini improvement, captured the moment the
    /// user clicks "G". Lets us offer "Original speichern" alongside
    /// "Verbessert speichern" without losing what was originally typed
    /// or dictated.
    /// </summary>
    private string? _originalBeforeImprove;

    private bool _isImproving;

    /// <summary>
    /// True nur wenn DIESER Dialog die aktuell laufende Aufnahme selbst
    /// gestartet hat. Der AudioRecorder ist prozessweit geteilt
    /// (<see cref="VoiceServiceProvider"/>) — nur eine Instanz darf das
    /// Mikrofon halten. Ohne dieses Flag wuerde der Dialog eine Aufnahme
    /// stoppen die das Voice-Overlay gestartet hat (im Closed-Handler) oder
    /// sie beim Mic-Klick uebernehmen. Mit dem Flag fasst der Dialog
    /// ausschliesslich seine EIGENE Aufnahme an.
    /// </summary>
    private bool _recordingStartedHere;

    /// <summary>
    /// True while the short-label field still holds an auto-generated value
    /// (after mic transcription or after Gemini improvement). The first
    /// moment the user manually types into the label field, this flips to
    /// false — and from then on the auto-titler never overwrites the
    /// user's wording. <c>null</c> means "no auto-title has ever been set
    /// in this session yet".
    /// </summary>
    private bool _labelIsAutoGenerated;
    private bool _suppressLabelChange;

    private static readonly Brush MicIdle      = new SolidColorBrush(Color.FromRgb(0x3D, 0x3D, 0x3D));
    private static readonly Brush MicRecording = new SolidColorBrush(Color.FromRgb(0xE5, 0x39, 0x35));
    private static readonly Brush MicTranscribing = new SolidColorBrush(Color.FromRgb(0xB8, 0x86, 0x0B));

    private DispatcherTimer? _pulseTimer;
    private bool _pulseBright;

    /// <summary>
    /// Verhindert Endlos-Schleifen wenn ein Checkbox-Handler den anderen
    /// programmatisch (un)setzt — die Pre/Post-Checkboxen schliessen sich
    /// gegenseitig aus, der Code muss seine eigenen Setter ignorieren.
    /// </summary>
    private bool _suppressCheckboxEvents;

    /// <summary>
    /// Erkennt einen bereits vorhandenen Wrapper der Form
    /// <c>Pre-Prompt: "..."</c> oder <c>Post-Prompt: "..."</c> am Anfang
    /// des Texts und liefert den inneren Text zurueck. Tolerant gegen
    /// Schreibvarianten (mit/ohne Bindestrich, mit/ohne Leerzeichen,
    /// Gross/Klein) — der Benutzer diktiert das ueber Whisper und die
    /// Schreibweise schwankt. Akzeptiert sowohl normale " als auch
    /// deutsche „...""-Anfuehrungszeichen.
    /// </summary>
    private static readonly Regex WrapperRegex = new(
        @"^\s*(?:Pre[-\s]?Prompt|Post[-\s]?Prompt)\s*:\s*[""„“](?<inner>[\s\S]*?)[""“”]\s*$",
        RegexOptions.IgnoreCase | RegexOptions.Compiled);

    /// <summary>
    /// Tracks the 10 hotkey toggle buttons (index 0 = "Kein", 1..9 = Strg+N).
    /// Built once in the constructor — kept around so the Save path can
    /// look up which one is checked without walking the visual tree.
    /// </summary>
    private readonly List<ToggleButton> _hotkeyButtons = new();

    public PromptEditDialog(
        string title,
        string initialLabel,
        string initialText,
        bool initialAlwaysOn,
        bool initialPrePrompt,
        bool initialPostPrompt,
        int? initialHotkey)
    {
        InitializeComponent();
        TitleText.Text = title;
        ShortLabelBox.Text = initialLabel;
        OriginalTextBox.Text = initialText;
        AlwaysOnCheckbox.IsChecked = initialAlwaysOn;
        BuildHotkeyButtons(initialHotkey);

        // Handler VOR den initialen IsChecked-Setzern verdrahten, damit der
        // Wrapper auch beim Laden eines bereits markierten Prompts auto-
        // matisch konsistent ist (idempotent: wenn Text schon gewrappt,
        // bleibt er identisch).
        PrePromptCheckbox.Checked    += PrePromptCheckbox_Checked;
        PrePromptCheckbox.Unchecked  += PrePromptCheckbox_Unchecked;
        PostPromptCheckbox.Checked   += PostPromptCheckbox_Checked;
        PostPromptCheckbox.Unchecked += PostPromptCheckbox_Unchecked;

        PrePromptCheckbox.IsChecked = initialPrePrompt;
        PostPromptCheckbox.IsChecked = initialPostPrompt;

        ShortLabelBox.Focus();
        ShortLabelBox.SelectAll();

        // Manual edits to the short-label field disarm the auto-titler. After
        // the very first user keystroke the label is treated as user-owned
        // and never overwritten by mic / Gemini-driven re-titling.
        ShortLabelBox.TextChanged += (_, _) =>
        {
            if (_suppressLabelChange) return;
            _labelIsAutoGenerated = false;
        };

        // Disable mic / G when their backing services aren't available
        // (e.g. no GROQ_API_KEY in .env, or no Gemini key).
        BtnMic.IsEnabled    = VoiceServiceProvider.RecorderAvailable;
        BtnGemini.IsEnabled = VoiceServiceProvider.GeminiAvailable;

        BtnCancel.Click += (_, _) => { Result = null; Close(); };
        BtnOk.Click      += (_, _) => SaveAs(OriginalTextBox.Text);
        BtnSaveOriginal.Click += (_, _) =>
        {
            // Persist what the user originally typed/dictated, even though
            // the textbox now shows the Gemini-improved version.
            SaveAs(_originalBeforeImprove ?? OriginalTextBox.Text);
        };
        BtnSaveImproved.Click += (_, _) => SaveAs(OriginalTextBox.Text);

        BtnMic.Click    += async (_, _) => await ToggleRecordingAsync();
        BtnGemini.Click += async (_, _) => await RunGeminiAsync();

        Closed += (_, _) =>
        {
            // Defensive: NUR eine Aufnahme stoppen, die DIESER Dialog selbst
            // gestartet hat — damit das Mikrofon nicht geleakt wird wenn der
            // Dialog mitten in der eigenen Aufnahme geschlossen wird. Eine vom
            // Voice-Overlay gestartete Aufnahme bleibt unangetastet; sonst
            // wuerde das Schliessen des Editier-Dialogs die laufende Overlay-
            // Aufnahme abwuergen (geteilter AudioRecorder).
            try
            {
                if (_recordingStartedHere && VoiceServiceProvider.Recorder?.IsRecording == true)
                    VoiceServiceProvider.Recorder.Stop();
            }
            catch { /* ignored */ }
            _pulseTimer?.Stop();
        };
    }

    private void SaveAs(string text)
    {
        var label = ShortLabelBox.Text?.Trim() ?? string.Empty;
        var safeText = (text ?? string.Empty).Trim();

        // If the user filled in only the prompt text (e.g. dictated via mic
        // and ran G without ever touching the short-label box) auto-derive a
        // label from the first few words. Beats the silent no-op the macOS
        // version still has.
        if (label.Length == 0 && safeText.Length > 0)
        {
            label = AutoLabelFromText(safeText);
            ShortLabelBox.Text = label;
        }

        if (label.Length == 0)
        {
            ShowStatus("Bitte eine Kurzbezeichnung eintragen oder Prompt-Text einsprechen.");
            ShortLabelBox.Focus();
            return;
        }

        // Refresh the timestamp suffix on every save — both for new
        // prompts and edits of existing ones. The label acts as a
        // "last modified" indicator, so re-saving a prompt should bump
        // it. Older behavior kept the original creation timestamp,
        // which made it impossible to tell at a glance which prompts
        // were recently revised.
        label = EnsureTimestampSuffix(label);

        Result = new PromptEditResult(
            label,
            text ?? string.Empty,
            AlwaysOnCheckbox.IsChecked == true,
            PrePromptCheckbox.IsChecked == true,
            PostPromptCheckbox.IsChecked == true,
            ReadSelectedHotkey());
        Close();
    }

    /// <summary>
    /// Builds the row of 10 toggle buttons ("Kein", "Strg+1" .. "Strg+9").
    /// Exactly one is checked at any moment — clicking another flips the
    /// previously checked one off via <see cref="OnHotkeyToggled"/>.
    /// Index 0 is the "Kein" button (= no binding); indices 1..9 carry the
    /// matching Strg+N number in their <see cref="FrameworkElement.Tag"/>.
    /// </summary>
    private void BuildHotkeyButtons(int? initial)
    {
        _hotkeyButtons.Clear();
        HotkeyPanel.Children.Clear();

        // Index 0: "Kein" — represents an unbound hotkey. Stored as Tag=0
        // so the lookup logic stays uniform (Tag carries the int value
        // for every button; 0 is the sentinel for "no binding").
        _hotkeyButtons.Add(MakeHotkeyButton("Kein", 0));
        for (int n = 1; n <= 9; n++)
        {
            _hotkeyButtons.Add(MakeHotkeyButton($"Strg+{n}", n));
        }

        // Pre-select the initial state. Null or out-of-range falls back to
        // "Kein" so the dialog never opens with no toggle checked at all.
        int initialIdx = (initial.HasValue && initial.Value >= 1 && initial.Value <= 9)
            ? initial.Value
            : 0;
        _hotkeyButtons[initialIdx].IsChecked = true;

        foreach (var b in _hotkeyButtons)
            HotkeyPanel.Children.Add(b);
    }

    private ToggleButton MakeHotkeyButton(string label, int value)
    {
        var btn = new ToggleButton
        {
            Content = label,
            Tag = value,
            MinWidth = 56,
            Padding = new Thickness(8, 4, 8, 4),
            Margin = new Thickness(0, 0, 6, 6),
            Background = new SolidColorBrush(Color.FromRgb(0x2D, 0x2D, 0x2D)),
            Foreground = new SolidColorBrush(Color.FromRgb(0xEE, 0xEE, 0xEE)),
            BorderBrush = new SolidColorBrush(Color.FromRgb(0x55, 0x55, 0x55)),
            BorderThickness = new Thickness(1),
            FontSize = 12,
            Cursor = System.Windows.Input.Cursors.Hand,
        };
        btn.Checked += OnHotkeyToggled;
        // Reject manual unchecks so the user can never end up with NO
        // toggle active. To clear a binding the user clicks "Kein"
        // instead — that's both the visible affordance and the saved
        // value (null in the Result record).
        btn.Click += (s, _) =>
        {
            if (s is ToggleButton tb && tb.IsChecked != true)
                tb.IsChecked = true;
        };
        return btn;
    }

    /// <summary>
    /// Mutual-exclusion handler: when one toggle becomes checked, every
    /// other toggle is forced off. We don't use a RadioButton group
    /// because the visual style we want (filled rectangular pill) reads
    /// much more cleanly as ToggleButton than as a styled RadioButton.
    /// </summary>
    private void OnHotkeyToggled(object sender, RoutedEventArgs e)
    {
        if (sender is not ToggleButton clicked) return;
        foreach (var b in _hotkeyButtons)
        {
            if (!ReferenceEquals(b, clicked) && b.IsChecked == true)
                b.IsChecked = false;
        }
    }

    /// <summary>
    /// Returns the currently active hotkey number, or null when "Kein"
    /// (Tag = 0) is selected. Defensive: if nothing is checked at all
    /// (shouldn't happen, but cheap insurance) we fall back to null.
    /// </summary>
    private int? ReadSelectedHotkey()
    {
        foreach (var b in _hotkeyButtons)
        {
            if (b.IsChecked == true && b.Tag is int n)
                return n == 0 ? (int?)null : n;
        }
        return null;
    }

    /// <summary>
    /// Sets a fresh "(dd.MM.yyyy, HH:mm)" suffix on the label, replacing
    /// any previously appended timestamp in our own format. Non-timestamp
    /// parenthesised notes the user may have typed (e.g. "(WIP)") are
    /// left in place — only our exact format is stripped so we don't
    /// trample on user content. Idempotent: calling multiple times only
    /// ever leaves one timestamp, always the most recent.
    /// </summary>
    private static string EnsureTimestampSuffix(string label)
    {
        // Match exactly our own format: " (dd.MM.yyyy, HH:mm)" possibly
        // followed by trailing whitespace. Only strip if the suffix
        // matches this shape — anything else is user content.
        var stripped = System.Text.RegularExpressions.Regex.Replace(
            label, @"\s*\(\d{2}\.\d{2}\.\d{4},\s*\d{2}:\d{2}\)\s*$", "").TrimEnd();
        var stamp = DateTime.Now.ToString("dd.MM.yyyy, HH:mm",
            System.Globalization.CultureInfo.InvariantCulture);
        return stripped + " (" + stamp + ")";
    }

    /// <summary>
    /// Builds a short label out of the first few non-empty words of the
    /// prompt text. Trims at ~40 chars so the bar stays compact, and falls
    /// back to "Prompt" if nothing usable is in there.
    /// </summary>
    private static string AutoLabelFromText(string text)
    {
        var words = text.Split(new[] { ' ', '\t', '\r', '\n' },
            StringSplitOptions.RemoveEmptyEntries);
        if (words.Length == 0) return "Prompt";
        var sb = new System.Text.StringBuilder();
        for (int i = 0; i < words.Length && i < 7; i++)
        {
            if (sb.Length > 0) sb.Append(' ');
            sb.Append(words[i]);
            if (sb.Length >= 40) break;
        }
        var s = sb.ToString().TrimEnd('.', ',', ';', ':', '!', '?');
        return s.Length == 0 ? "Prompt" : s;
    }

    public static PromptEditResult? Ask(
        Window owner, string title, string label, string text,
        bool alwaysOn, bool prePrompt, bool postPrompt, int? hotkey)
    {
        var dlg = new PromptEditDialog(
            title, label, text, alwaysOn, prePrompt, postPrompt, hotkey)
        {
            Owner = owner
        };
        dlg.ShowDialog();
        return dlg.Result;
    }

    // ──────────────── Mic-Recording ────────────────

    /// <summary>
    /// Toggles the dictation recorder. While recording the mic button
    /// pulses red; on stop the wav is sent to Groq Whisper and the
    /// transcribed text is appended to the prompt-text box. The button
    /// briefly shows an amber "transcribing" state during the API call.
    /// </summary>
    private async Task ToggleRecordingAsync()
    {
        var recorder = VoiceServiceProvider.Recorder;
        var groq     = VoiceServiceProvider.Groq;
        if (recorder is null || groq is null)
        {
            ShowStatus("Mic-Aufnahme nicht verfuegbar (kein GROQ_API_KEY in .env).");
            return;
        }

        // Der AudioRecorder ist prozessweit geteilt. Laeuft bereits eine
        // Aufnahme, die NICHT dieser Dialog gestartet hat (z.B. die Voice-
        // Overlay-Aufnahme), duerfen wir sie weder stoppen noch ihr Audio in
        // dieses Editierfeld umleiten — sonst bricht die Overlay-Aufnahme ab.
        if (recorder.IsRecording && !_recordingStartedHere)
        {
            ShowStatus("Es laeuft bereits eine Aufnahme (Voice-Overlay). Bitte zuerst dort stoppen.");
            return;
        }

        if (recorder.IsRecording)
        {
            // ── Stop & transcribe ──
            StopPulse();
            BtnMic.Background = MicTranscribing;
            ShowStatus("Transkribiere...");
            string? wavPath = null;
            try
            {
                wavPath = recorder.Stop();
                // Unsere Aufnahme ist beendet — Eigentum freigeben, damit ein
                // spaeterer Closed-Handler sie nicht erneut anzufassen versucht.
                _recordingStartedHere = false;
                if (string.IsNullOrEmpty(wavPath))
                {
                    ShowStatus("Aufnahme leer.");
                    BtnMic.Background = MicIdle;
                    return;
                }
                var text = await groq.TranscribeAsync(wavPath);
                AppendToPromptText(text);
                ShowStatus($"{text.Length} Zeichen eingefuegt.");
                // Auto-title only if the user hasn't already typed a custom
                // label themselves. AutoTitleAsync silently no-ops when
                // Gemini isn't configured.
                _ = AutoTitleAsync();
            }
            catch (Exception ex)
            {
                ShowStatus($"Transkription fehlgeschlagen: {ex.Message}");
            }
            finally
            {
                BtnMic.Background = MicIdle;
                if (!string.IsNullOrEmpty(wavPath))
                    TryDeleteFile(wavPath);
            }
            return;
        }

        // ── Start ──
        try
        {
            recorder.Start();
            _recordingStartedHere = true;
            StartPulse();
            ShowStatus("Aufnahme laeuft. Klick erneut auf Mic zum Stoppen.");
        }
        catch (Exception ex)
        {
            ShowStatus($"Aufnahme konnte nicht gestartet werden: {ex.Message}");
            BtnMic.Background = MicIdle;
        }
    }

    private void AppendToPromptText(string newText)
    {
        if (string.IsNullOrWhiteSpace(newText)) return;
        var current = OriginalTextBox.Text ?? string.Empty;
        if (current.Length > 0 && !current.EndsWith(' ') && !current.EndsWith('\n'))
            current += " ";
        OriginalTextBox.Text = current + newText.Trim();
        // Scroll caret into view at end so the user sees the new text land.
        OriginalTextBox.CaretIndex = OriginalTextBox.Text.Length;
        OriginalTextBox.ScrollToEnd();
    }

    private void StartPulse()
    {
        _pulseTimer ??= new DispatcherTimer { Interval = TimeSpan.FromMilliseconds(500) };
        _pulseTimer.Tick -= OnPulseTick;
        _pulseTimer.Tick += OnPulseTick;
        _pulseBright = false;
        BtnMic.Background = MicRecording;
        _pulseTimer.Start();
    }

    private void StopPulse()
    {
        _pulseTimer?.Stop();
        _pulseBright = false;
    }

    private void OnPulseTick(object? sender, EventArgs e)
    {
        _pulseBright = !_pulseBright;
        BtnMic.Background = _pulseBright
            ? new SolidColorBrush(Color.FromRgb(0xFF, 0x66, 0x66))
            : MicRecording;
    }

    // ──────────────── Gemini-Verbesserung ────────────────

    /// <summary>
    /// Sends the current prompt text to Gemini for cleanup. On success the
    /// textbox shows the improved version, and the footer switches from a
    /// single "Speichern" button to two ("Original speichern" / "Verbessert
    /// speichern"), so the user can pick which version to persist. The
    /// original text is held in <see cref="_originalBeforeImprove"/>.
    /// </summary>
    private async Task RunGeminiAsync()
    {
        if (_isImproving) return;
        var gemini = VoiceServiceProvider.Gemini;
        if (gemini is null)
        {
            ShowStatus("Gemini nicht verfuegbar (kein GEMINI_API_KEY in .env).");
            return;
        }
        var current = OriginalTextBox.Text?.Trim();
        if (string.IsNullOrEmpty(current))
        {
            ShowStatus("Kein Text zum Verbessern.");
            return;
        }

        _isImproving = true;
        BtnGemini.IsEnabled = false;
        BtnMic.IsEnabled = false;
        ShowStatus("Verbessere mit Gemini...");
        try
        {
            // PromptBoard-Editor nutzt das Prompt-Engineer-Template (rohes
            // Diktat → kopierfertiger Claude-Code-CLI-Prompt). Das Diktat-
            // Cleanup-Template bleibt dem Overlay-Pfad vorbehalten.
            var improved = await gemini.BuildClaudeCodePromptAsync(current);
            if (string.IsNullOrWhiteSpace(improved))
            {
                ShowStatus("Gemini lieferte leere Antwort.");
                return;
            }
            // Capture the user's original ONLY on the first improvement so
            // multiple back-to-back G clicks don't lose the very first text.
            _originalBeforeImprove ??= current;
            OriginalTextBox.Text = improved;
            ShowImprovedFooter();
            ShowStatus($"Verbessert ({improved.Length} Zeichen). Original im Hintergrund erhalten.");
            // Re-title against the improved text — overwrites a previous
            // auto-title but never a manually edited label.
            _ = AutoTitleAsync();
        }
        catch (Exception ex)
        {
            ShowStatus($"Gemini-Verbesserung fehlgeschlagen: {ex.Message}");
        }
        finally
        {
            _isImproving = false;
            BtnGemini.IsEnabled = VoiceServiceProvider.GeminiAvailable;
            BtnMic.IsEnabled    = VoiceServiceProvider.RecorderAvailable;
        }
    }

    private void ShowImprovedFooter()
    {
        BtnOk.Visibility           = Visibility.Collapsed;
        DualSavePanel.Visibility   = Visibility.Visible;
    }

    // ──────────────── Auto-Titel via Gemini ────────────────

    /// <summary>
    /// Asks Gemini for a max-3-word headline of the current prompt text and
    /// drops it into the short-label box. Skipped silently when:
    /// <list type="bullet">
    ///   <item>Gemini isn't configured (no API key).</item>
    ///   <item>The prompt text is empty.</item>
    ///   <item>The user has already typed a custom label themselves
    ///         (see <see cref="_labelIsAutoGenerated"/>).</item>
    /// </list>
    /// Called after mic transcription AND after Gemini improvement so the
    /// label always reflects the freshest version of the text.
    /// </summary>
    private async Task AutoTitleAsync()
    {
        var gemini = VoiceServiceProvider.Gemini;
        if (gemini is null) return;

        var currentLabel = (ShortLabelBox.Text ?? string.Empty).Trim();
        // Skip when the field already holds something the user typed.
        // First-time auto-fill (currentLabel empty) or replacing a previous
        // auto-fill (_labelIsAutoGenerated true) are both fine.
        if (currentLabel.Length > 0 && !_labelIsAutoGenerated) return;

        var text = (OriginalTextBox.Text ?? string.Empty).Trim();
        if (text.Length == 0) return;

        try
        {
            var prompt =
                "Schreibe eine sehr kurze Ueberschrift (genau MAXIMAL 3 Woerter, " +
                "ohne Anfuehrungszeichen, ohne Punkt am Ende, im Stil eines Datei-Tags) " +
                "fuer den folgenden Prompt-Text. Gib NUR die Ueberschrift aus, sonst nichts.\n\n" +
                "Prompt-Text:\n" + text;
            var headline = await gemini.CorrectTextAsync(prompt);
            headline = SanitizeHeadline(headline);
            if (headline.Length == 0) return;

            // Suppress the TextChanged disarm path while we write the auto
            // title — otherwise our own write would flip _labelIsAutoGenerated
            // to false and any subsequent re-title would be skipped.
            _suppressLabelChange = true;
            ShortLabelBox.Text = headline;
            _suppressLabelChange = false;
            _labelIsAutoGenerated = true;
        }
        catch (Exception ex)
        {
            Console.WriteLine($"[PromptEditDialog] AutoTitle failed: {ex.Message}");
        }
    }

    /// <summary>
    /// Defensive trim of the model output. Gemini sometimes wraps replies in
    /// quotes, adds trailing periods, or returns more than 3 words despite
    /// the explicit instruction. We hard-cap to 3 words here so the bar
    /// stays compact regardless of the model's mood.
    /// </summary>
    private static string SanitizeHeadline(string raw)
    {
        if (string.IsNullOrWhiteSpace(raw)) return string.Empty;
        // Take first non-empty line only.
        var line = raw.Trim().Split('\n')[0].Trim();
        line = line.Trim('"', '\'', '.', ' ', '\t', '*', '#', '`', '–', '—');
        // Cap to 3 words.
        var words = line.Split(' ', StringSplitOptions.RemoveEmptyEntries);
        if (words.Length == 0) return string.Empty;
        var n = Math.Min(3, words.Length);
        return string.Join(' ', words, 0, n);
    }

    // ──────────────── Misc helpers ────────────────

    private void ShowStatus(string text)
    {
        StatusText.Text = text;
    }

    private static void TryDeleteFile(string path)
    {
        try { if (File.Exists(path)) File.Delete(path); }
        catch { /* keep the temp file silently if delete fails */ }
    }

    // ──────────────── Pre/Post-Prompt Wrapper ────────────────

    /// <summary>
    /// Wenn der Benutzer "Pre-Prompt" ankreuzt, wird der Text im Prompt-Feld
    /// automatisch in das Format <c>Pre-Prompt: "&lt;text&gt;"</c> umgeschrieben.
    /// Pre und Post sind gegenseitig ausschliessend — ein gleichzeitig
    /// gesetztes Post-Haekchen wird automatisch entfernt.
    /// </summary>
    private void PrePromptCheckbox_Checked(object sender, RoutedEventArgs e)
    {
        if (_suppressCheckboxEvents) return;
        _suppressCheckboxEvents = true;
        try
        {
            if (PostPromptCheckbox.IsChecked == true)
                PostPromptCheckbox.IsChecked = false;
            WrapTextWithLabel("Pre-Prompt");
        }
        finally { _suppressCheckboxEvents = false; }
    }

    /// <summary>
    /// Beim Entfernen des Pre-Haekchens wird der Wrapper aus dem Text-
    /// feld zurueckgenommen (wenn er noch da ist) — der Benutzer sieht
    /// danach den nackten Prompt-Text.
    /// </summary>
    private void PrePromptCheckbox_Unchecked(object sender, RoutedEventArgs e)
    {
        if (_suppressCheckboxEvents) return;
        _suppressCheckboxEvents = true;
        try { UnwrapText(); }
        finally { _suppressCheckboxEvents = false; }
    }

    /// <summary>Spiegelbildlich zu <see cref="PrePromptCheckbox_Checked"/> fuer Post-Prompt.</summary>
    private void PostPromptCheckbox_Checked(object sender, RoutedEventArgs e)
    {
        if (_suppressCheckboxEvents) return;
        _suppressCheckboxEvents = true;
        try
        {
            if (PrePromptCheckbox.IsChecked == true)
                PrePromptCheckbox.IsChecked = false;
            WrapTextWithLabel("Post-Prompt");
        }
        finally { _suppressCheckboxEvents = false; }
    }

    private void PostPromptCheckbox_Unchecked(object sender, RoutedEventArgs e)
    {
        if (_suppressCheckboxEvents) return;
        _suppressCheckboxEvents = true;
        try { UnwrapText(); }
        finally { _suppressCheckboxEvents = false; }
    }

    /// <summary>
    /// Setzt den Wrapper <c>{label}: "&lt;text&gt;"</c> um den aktuellen
    /// Text. Falls schon ein Wrapper drin ist (auch der andere Typ),
    /// wird er erst entfernt — danach genau einer.
    /// </summary>
    private void WrapTextWithLabel(string label)
    {
        var raw = StripExistingWrapper(OriginalTextBox.Text ?? string.Empty);
        OriginalTextBox.Text = $"{label}: \"{raw}\"";
    }

    /// <summary>Entfernt einen vorhandenen Pre/Post-Wrapper, sonst No-Op.</summary>
    private void UnwrapText()
    {
        OriginalTextBox.Text = StripExistingWrapper(OriginalTextBox.Text ?? string.Empty);
    }

    private static string StripExistingWrapper(string text)
    {
        if (string.IsNullOrEmpty(text)) return text ?? string.Empty;
        var match = WrapperRegex.Match(text);
        return match.Success ? match.Groups["inner"].Value : text;
    }
}
