using System;
using System.IO;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Media;
using System.Windows.Threading;
using TerminalVoiceOverlay.Services;

namespace TerminalVoiceOverlay.Views;

public sealed record PromptEditResult(string ShortLabel, string OriginalText, bool IsAlwaysOn);

public partial class PromptEditDialog : Window
{
    public PromptEditResult? Result { get; private set; }

    /// <summary>
    /// Original text BEFORE Gemini improvement, captured the moment the
    /// user clicks "G". Lets us offer "Original speichern" alongside
    /// "Verbessert speichern" without losing what was originally typed
    /// or dictated.
    /// </summary>
    private string? _originalBeforeImprove;

    private bool _isImproving;

    /// <summary>
    /// True while the short-label field still holds an auto-generated value
    /// (after mic transcription or after Gemini improvement). The first
    /// moment the user manually types into the label field, this flips to
    /// false — and from then on the auto-titler never overwrites the
    /// user's wording. <c>null</c> means "no auto-title has ever been set
    /// in this session yet".
    /// </summary>
    private bool _labelIsAutoGenerated;
    private bool _suppressLabelChange;

    private static readonly Brush MicIdle      = new SolidColorBrush(Color.FromRgb(0x3D, 0x3D, 0x3D));
    private static readonly Brush MicRecording = new SolidColorBrush(Color.FromRgb(0xE5, 0x39, 0x35));
    private static readonly Brush MicTranscribing = new SolidColorBrush(Color.FromRgb(0xB8, 0x86, 0x0B));

    private DispatcherTimer? _pulseTimer;
    private bool _pulseBright;

    public PromptEditDialog(
        string title,
        string initialLabel,
        string initialText,
        bool initialAlwaysOn)
    {
        InitializeComponent();
        TitleText.Text = title;
        ShortLabelBox.Text = initialLabel;
        OriginalTextBox.Text = initialText;
        AlwaysOnCheckbox.IsChecked = initialAlwaysOn;

        ShortLabelBox.Focus();
        ShortLabelBox.SelectAll();

        // Manual edits to the short-label field disarm the auto-titler. After
        // the very first user keystroke the label is treated as user-owned
        // and never overwritten by mic / Gemini-driven re-titling.
        ShortLabelBox.TextChanged += (_, _) =>
        {
            if (_suppressLabelChange) return;
            _labelIsAutoGenerated = false;
        };

        // Disable mic / G when their backing services aren't available
        // (e.g. no GROQ_API_KEY in .env, or no Gemini key).
        BtnMic.IsEnabled    = VoiceServiceProvider.RecorderAvailable;
        BtnGemini.IsEnabled = VoiceServiceProvider.GeminiAvailable;

        BtnCancel.Click += (_, _) => { Result = null; Close(); };
        BtnOk.Click      += (_, _) => SaveAs(OriginalTextBox.Text);
        BtnSaveOriginal.Click += (_, _) =>
        {
            // Persist what the user originally typed/dictated, even though
            // the textbox now shows the Gemini-improved version.
            SaveAs(_originalBeforeImprove ?? OriginalTextBox.Text);
        };
        BtnSaveImproved.Click += (_, _) => SaveAs(OriginalTextBox.Text);

        BtnMic.Click    += async (_, _) => await ToggleRecordingAsync();
        BtnGemini.Click += async (_, _) => await RunGeminiAsync();

        Closed += (_, _) =>
        {
            // Defensive: stop any in-progress recording so we never leak
            // the microphone if the dialog is closed mid-recording.
            try
            {
                if (VoiceServiceProvider.Recorder?.IsRecording == true)
                    VoiceServiceProvider.Recorder.Stop();
            }
            catch { /* ignored */ }
            _pulseTimer?.Stop();
        };
    }

    private void SaveAs(string text)
    {
        var label = ShortLabelBox.Text?.Trim() ?? string.Empty;
        var safeText = (text ?? string.Empty).Trim();

        // If the user filled in only the prompt text (e.g. dictated via mic
        // and ran G without ever touching the short-label box) auto-derive a
        // label from the first few words. Beats the silent no-op the macOS
        // version still has.
        if (label.Length == 0 && safeText.Length > 0)
        {
            label = AutoLabelFromText(safeText);
            ShortLabelBox.Text = label;
        }

        if (label.Length == 0)
        {
            ShowStatus("Bitte eine Kurzbezeichnung eintragen oder Prompt-Text einsprechen.");
            ShortLabelBox.Focus();
            return;
        }

        // Append a creation timestamp once. Existing prompts that already
        // carry a "(dd.MM.yyyy, HH:mm)" suffix keep theirs — we never
        // overwrite the original creation time.
        label = EnsureTimestampSuffix(label);

        Result = new PromptEditResult(label, text ?? string.Empty, AlwaysOnCheckbox.IsChecked == true);
        Close();
    }

    /// <summary>
    /// Adds "(dd.MM.yyyy, HH:mm)" to the end of the label if the label
    /// doesn't already end in a parenthesised timestamp. Idempotent so
    /// editing a prompt repeatedly never stacks multiple timestamps.
    /// </summary>
    private static string EnsureTimestampSuffix(string label)
    {
        // Tolerant match: any "(...)" at the very end, regardless of whether
        // it's our timestamp or some other parenthesised note the user
        // typed. We don't replace it — the user's parenthesis wins.
        if (System.Text.RegularExpressions.Regex.IsMatch(label, @"\([^)]*\)\s*$"))
            return label;
        var stamp = DateTime.Now.ToString("dd.MM.yyyy, HH:mm",
            System.Globalization.CultureInfo.InvariantCulture);
        return label + " (" + stamp + ")";
    }

    /// <summary>
    /// Builds a short label out of the first few non-empty words of the
    /// prompt text. Trims at ~40 chars so the bar stays compact, and falls
    /// back to "Prompt" if nothing usable is in there.
    /// </summary>
    private static string AutoLabelFromText(string text)
    {
        var words = text.Split(new[] { ' ', '\t', '\r', '\n' },
            StringSplitOptions.RemoveEmptyEntries);
        if (words.Length == 0) return "Prompt";
        var sb = new System.Text.StringBuilder();
        for (int i = 0; i < words.Length && i < 7; i++)
        {
            if (sb.Length > 0) sb.Append(' ');
            sb.Append(words[i]);
            if (sb.Length >= 40) break;
        }
        var s = sb.ToString().TrimEnd('.', ',', ';', ':', '!', '?');
        return s.Length == 0 ? "Prompt" : s;
    }

    public static PromptEditResult? Ask(
        Window owner, string title, string label, string text, bool alwaysOn)
    {
        var dlg = new PromptEditDialog(title, label, text, alwaysOn) { Owner = owner };
        dlg.ShowDialog();
        return dlg.Result;
    }

    // ──────────────── Mic-Recording ────────────────

    /// <summary>
    /// Toggles the dictation recorder. While recording the mic button
    /// pulses red; on stop the wav is sent to Groq Whisper and the
    /// transcribed text is appended to the prompt-text box. The button
    /// briefly shows an amber "transcribing" state during the API call.
    /// </summary>
    private async Task ToggleRecordingAsync()
    {
        var recorder = VoiceServiceProvider.Recorder;
        var groq     = VoiceServiceProvider.Groq;
        if (recorder is null || groq is null)
        {
            ShowStatus("Mic-Aufnahme nicht verfuegbar (kein GROQ_API_KEY in .env).");
            return;
        }

        if (recorder.IsRecording)
        {
            // ── Stop & transcribe ──
            StopPulse();
            BtnMic.Background = MicTranscribing;
            ShowStatus("Transkribiere...");
            string? wavPath = null;
            try
            {
                wavPath = recorder.Stop();
                if (string.IsNullOrEmpty(wavPath))
                {
                    ShowStatus("Aufnahme leer.");
                    BtnMic.Background = MicIdle;
                    return;
                }
                var text = await groq.TranscribeAsync(wavPath);
                AppendToPromptText(text);
                ShowStatus($"{text.Length} Zeichen eingefuegt.");
                // Auto-title only if the user hasn't already typed a custom
                // label themselves. AutoTitleAsync silently no-ops when
                // Gemini isn't configured.
                _ = AutoTitleAsync();
            }
            catch (Exception ex)
            {
                ShowStatus($"Transkription fehlgeschlagen: {ex.Message}");
            }
            finally
            {
                BtnMic.Background = MicIdle;
                if (!string.IsNullOrEmpty(wavPath))
                    TryDeleteFile(wavPath);
            }
            return;
        }

        // ── Start ──
        try
        {
            recorder.Start();
            StartPulse();
            ShowStatus("Aufnahme laeuft. Klick erneut auf Mic zum Stoppen.");
        }
        catch (Exception ex)
        {
            ShowStatus($"Aufnahme konnte nicht gestartet werden: {ex.Message}");
            BtnMic.Background = MicIdle;
        }
    }

    private void AppendToPromptText(string newText)
    {
        if (string.IsNullOrWhiteSpace(newText)) return;
        var current = OriginalTextBox.Text ?? string.Empty;
        if (current.Length > 0 && !current.EndsWith(' ') && !current.EndsWith('\n'))
            current += " ";
        OriginalTextBox.Text = current + newText.Trim();
        // Scroll caret into view at end so the user sees the new text land.
        OriginalTextBox.CaretIndex = OriginalTextBox.Text.Length;
        OriginalTextBox.ScrollToEnd();
    }

    private void StartPulse()
    {
        _pulseTimer ??= new DispatcherTimer { Interval = TimeSpan.FromMilliseconds(500) };
        _pulseTimer.Tick -= OnPulseTick;
        _pulseTimer.Tick += OnPulseTick;
        _pulseBright = false;
        BtnMic.Background = MicRecording;
        _pulseTimer.Start();
    }

    private void StopPulse()
    {
        _pulseTimer?.Stop();
        _pulseBright = false;
    }

    private void OnPulseTick(object? sender, EventArgs e)
    {
        _pulseBright = !_pulseBright;
        BtnMic.Background = _pulseBright
            ? new SolidColorBrush(Color.FromRgb(0xFF, 0x66, 0x66))
            : MicRecording;
    }

    // ──────────────── Gemini-Verbesserung ────────────────

    /// <summary>
    /// Sends the current prompt text to Gemini for cleanup. On success the
    /// textbox shows the improved version, and the footer switches from a
    /// single "Speichern" button to two ("Original speichern" / "Verbessert
    /// speichern"), so the user can pick which version to persist. The
    /// original text is held in <see cref="_originalBeforeImprove"/>.
    /// </summary>
    private async Task RunGeminiAsync()
    {
        if (_isImproving) return;
        var gemini = VoiceServiceProvider.Gemini;
        if (gemini is null)
        {
            ShowStatus("Gemini nicht verfuegbar (kein GEMINI_API_KEY in .env).");
            return;
        }
        var current = OriginalTextBox.Text?.Trim();
        if (string.IsNullOrEmpty(current))
        {
            ShowStatus("Kein Text zum Verbessern.");
            return;
        }

        _isImproving = true;
        BtnGemini.IsEnabled = false;
        BtnMic.IsEnabled = false;
        ShowStatus("Verbessere mit Gemini...");
        try
        {
            // PromptBoard-Editor nutzt das Prompt-Engineer-Template (rohes
            // Diktat → kopierfertiger Claude-Code-CLI-Prompt). Das Diktat-
            // Cleanup-Template bleibt dem Overlay-Pfad vorbehalten.
            var improved = await gemini.BuildClaudeCodePromptAsync(current);
            if (string.IsNullOrWhiteSpace(improved))
            {
                ShowStatus("Gemini lieferte leere Antwort.");
                return;
            }
            // Capture the user's original ONLY on the first improvement so
            // multiple back-to-back G clicks don't lose the very first text.
            _originalBeforeImprove ??= current;
            OriginalTextBox.Text = improved;
            ShowImprovedFooter();
            ShowStatus($"Verbessert ({improved.Length} Zeichen). Original im Hintergrund erhalten.");
            // Re-title against the improved text — overwrites a previous
            // auto-title but never a manually edited label.
            _ = AutoTitleAsync();
        }
        catch (Exception ex)
        {
            ShowStatus($"Gemini-Verbesserung fehlgeschlagen: {ex.Message}");
        }
        finally
        {
            _isImproving = false;
            BtnGemini.IsEnabled = VoiceServiceProvider.GeminiAvailable;
            BtnMic.IsEnabled    = VoiceServiceProvider.RecorderAvailable;
        }
    }

    private void ShowImprovedFooter()
    {
        BtnOk.Visibility           = Visibility.Collapsed;
        DualSavePanel.Visibility   = Visibility.Visible;
    }

    // ──────────────── Auto-Titel via Gemini ────────────────

    /// <summary>
    /// Asks Gemini for a max-3-word headline of the current prompt text and
    /// drops it into the short-label box. Skipped silently when:
    /// <list type="bullet">
    ///   <item>Gemini isn't configured (no API key).</item>
    ///   <item>The prompt text is empty.</item>
    ///   <item>The user has already typed a custom label themselves
    ///         (see <see cref="_labelIsAutoGenerated"/>).</item>
    /// </list>
    /// Called after mic transcription AND after Gemini improvement so the
    /// label always reflects the freshest version of the text.
    /// </summary>
    private async Task AutoTitleAsync()
    {
        var gemini = VoiceServiceProvider.Gemini;
        if (gemini is null) return;

        var currentLabel = (ShortLabelBox.Text ?? string.Empty).Trim();
        // Skip when the field already holds something the user typed.
        // First-time auto-fill (currentLabel empty) or replacing a previous
        // auto-fill (_labelIsAutoGenerated true) are both fine.
        if (currentLabel.Length > 0 && !_labelIsAutoGenerated) return;

        var text = (OriginalTextBox.Text ?? string.Empty).Trim();
        if (text.Length == 0) return;

        try
        {
            var prompt =
                "Schreibe eine sehr kurze Ueberschrift (genau MAXIMAL 3 Woerter, " +
                "ohne Anfuehrungszeichen, ohne Punkt am Ende, im Stil eines Datei-Tags) " +
                "fuer den folgenden Prompt-Text. Gib NUR die Ueberschrift aus, sonst nichts.\n\n" +
                "Prompt-Text:\n" + text;
            var headline = await gemini.CorrectTextAsync(prompt);
            headline = SanitizeHeadline(headline);
            if (headline.Length == 0) return;

            // Suppress the TextChanged disarm path while we write the auto
            // title — otherwise our own write would flip _labelIsAutoGenerated
            // to false and any subsequent re-title would be skipped.
            _suppressLabelChange = true;
            ShortLabelBox.Text = headline;
            _suppressLabelChange = false;
            _labelIsAutoGenerated = true;
        }
        catch (Exception ex)
        {
            Console.WriteLine($"[PromptEditDialog] AutoTitle failed: {ex.Message}");
        }
    }

    /// <summary>
    /// Defensive trim of the model output. Gemini sometimes wraps replies in
    /// quotes, adds trailing periods, or returns more than 3 words despite
    /// the explicit instruction. We hard-cap to 3 words here so the bar
    /// stays compact regardless of the model's mood.
    /// </summary>
    private static string SanitizeHeadline(string raw)
    {
        if (string.IsNullOrWhiteSpace(raw)) return string.Empty;
        // Take first non-empty line only.
        var line = raw.Trim().Split('\n')[0].Trim();
        line = line.Trim('"', '\'', '.', ' ', '\t', '*', '#', '`', '–', '—');
        // Cap to 3 words.
        var words = line.Split(' ', StringSplitOptions.RemoveEmptyEntries);
        if (words.Length == 0) return string.Empty;
        var n = Math.Min(3, words.Length);
        return string.Join(' ', words, 0, n);
    }

    // ──────────────── Misc helpers ────────────────

    private void ShowStatus(string text)
    {
        StatusText.Text = text;
    }

    private static void TryDeleteFile(string path)
    {
        try { if (File.Exists(path)) File.Delete(path); }
        catch { /* keep the temp file silently if delete fails */ }
    }
}
